name: "refresh"

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install dpkg-dev bzip2 xz-utils zstd -y

      - name: Refresh Packages
        run: |
          rm -rf ./Packages*
          dpkg-scanpackages -m ./debs /dev/null > ./Packages
          bzip2 -k -9 Packages
          xz -k -9 --extreme Packages
          zstd -q -19 Packages

      - name: Commit and push changes
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
          git add .
          git diff --quiet || git commit -m 'Refresh Packages and Release'
          git push

      - name: Delete old workflow runs
        run: |
          gh api -X GET "/repos/${{ github.repository }}/actions/runs" \
            --paginate -F status=completed -q '.workflow_runs[] | select(.head_branch == "main") | .id' \
            | xargs -n1 -I {} gh api -X DELETE "/repos/${{ github.repository }}/actions/runs/{}"
